/* Generated By:JavaCC: Do not edit this line. ToolTreeConstants.java Version 5.0 */
package parser;

public interface ToolTreeConstants
{
  public int JJTCLASS = 0;
  public int JJTINSTANCE = 1;
  public int JJTTYPE = 2;
  public int JJTPARAMETERS = 3;
  public int JJTEVENT = 4;
  public int JJTCODE = 5;
  public int JJTSTART = 6;
  public int JJTPROGRAM = 7;


  public String[] jjtNodeName = {
    "Class",
    "Instance",
    "Type",
    "Parameters",
    "Event",
    "Code",
    "Start",
    "Program",
  };
}
/* JavaCC - OriginalChecksum=29afd40739945de372b089eefeea8060 (do not edit this line) */
