/* Generated By:JavaCC: Do not edit this line. ToolTreeConstants.java Version 5.0 */
package parser;

public interface ToolTreeConstants
{
  public int JJTBLCK = 0;
  public int JJTBLOCK = 1;
  public int JJTIMPORTSKERNELINCLUDES = 2;
  public int JJTIMPORTSAPPLLICATIONIMPORTS = 3;
  public int JJTIMPORTSKERNELSIDE = 4;
  public int JJTIMPORTSAPPLICATIONSIDE = 5;
  public int JJTIMPORTSMAIN = 6;
  public int JJTTIMERS = 7;
  public int JJTTIMERSMAIN = 8;
  public int JJTSTATES = 9;
  public int JJTSTATESMAIN = 10;
  public int JJTEVENTNAME = 11;
  public int JJTCLASSNAME = 12;
  public int JJTTYPE = 13;
  public int JJTPARAMETERS = 14;
  public int JJTCALLPARAMETERS = 15;
  public int JJTEVENTNAMECALL = 16;
  public int JJTEVENTINSTANCE = 17;
  public int JJTEVENTSOPTIONAL = 18;
  public int JJTEVENTCOLLECTION = 19;
  public int JJTTIMEREVENTDEF = 20;
  public int JJTEVENTDEFINED = 21;
  public int JJTEVENTSMAIN = 22;
  public int JJTCONDITIONNAME = 23;
  public int JJTTIMERNAME = 24;
  public int JJTTIMERVALUE = 25;
  public int JJTCONDITIONSDEF = 26;
  public int JJTTIMERCONDITIONS = 27;
  public int JJTCONDITIONSDEFINED = 28;
  public int JJTCONDITIONSMAIN = 29;
  public int JJTACTIONNAME = 30;
  public int JJTACTIONSDEF = 31;
  public int JJTTIMERACTIONDEF = 32;
  public int JJTACTIONSDEFINED = 33;
  public int JJTACTIONSMAIN = 34;
  public int JJTRULECONDITION = 35;
  public int JJTRULESDEFINED = 36;
  public int JJTRULESMAIN = 37;
  public int JJTGLOBALMAIN = 38;
  public int JJTPROGRAM = 39;


  public String[] jjtNodeName = {
    "Blck",
    "Block",
    "ImportsKernelIncludes",
    "ImportsAppllicationImports",
    "ImportsKernelSide",
    "ImportsApplicationSide",
    "ImportsMain",
    "Timers",
    "TimersMain",
    "States",
    "StatesMain",
    "EventName",
    "ClassName",
    "Type",
    "Parameters",
    "CallParameters",
    "EventNameCall",
    "EventInstance",
    "EventsOptional",
    "EventCollection",
    "TimerEventDef",
    "EventDefined",
    "EventsMain",
    "ConditionName",
    "TimerName",
    "TimerValue",
    "ConditionsDef",
    "TimerConditions",
    "ConditionsDefined",
    "ConditionsMain",
    "ActionName",
    "ActionsDef",
    "TimerActionDef",
    "ActionsDefined",
    "ActionsMain",
    "RuleCondition",
    "RulesDefined",
    "RulesMain",
    "GlobalMain",
    "Program",
  };
}
/* JavaCC - OriginalChecksum=82593e50a01d1fab1d9f71eb72fcb272 (do not edit this line) */
